<!doctype>
<html>
    <head>
        <title>Student Summary Balance</title>
            {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">      --}}

        <style>
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 10px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2, .h3, h3 {
                font-size: 30px;
                font-weight: 400;
                margin-top : 0;
            }
            .container {
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 5px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-red {
                color: #a94442;
            }
            .text-green {
                color: #00a65a !important;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
            .hidden {
                display: none!important;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Student Monthly Balance Summary Report</h2>
            <div>
            </div>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            <br>
            {{--  <div class="text-right">Total Received Payment <strong class="text-danger"><h3>P {{ ($payment_sum->sum ? a_number_format($payment_sum->sum) : '0.00') }}</h3></strong></div>  --}}
            <div class="">Period <strong>{{ $mon_str_dispay }}</strong></div>
            <br>
            <table class="table table-bordered">
                <tr>
                    <th>Grade</th>
                    <th>Total Tuition</th>
                    <th>Total DP</th>
                    {{--  <th>Section</th>  --}}
                    @for($i=$mon_from-1;$i<$mon_to;$i++)
                    {{--  @for($i=0;$i<10;$i++)  --}}
                        <th>{{ $months_array[$i] }}</th>
                    @endfor
                    <th>Total Payment</th>
                    <th>Total Discount</th>
                    <th>Balance</th>
                </tr>
            <tbody>
                <?php  
                    $total_receivables  = 0; 
                    $month_total        = [
                        'm1' => 0,'m2' => 0,
                        'm3' => 0,'m4' => 0,
                        'm5' => 0,'m6' => 0,
                        'm7' => 0,'m8' => 0,
                        'm9' => 0,'m10' => 0
                    ] ;
                    $grand_total_discount = 0;
                    $grand_total_payment  = 0;
                    $grand_total_tuition  = 0;
                    $grand_total_balance  = 0;
                    $grand_total_dp       = 0;

                    $total_rm = 0;
                ?>
                @foreach ($grade_balance as $key => $balance)
                    <?php
                        
                        $total_discount = $student_discount[$key];
                                    /*= (
                                        $balance['school_subsidy']
                                        +
                                        $balance['gov_subsidy']
                                        +
                                        $balance['st_joseph_discount']
                                        +
                                        ($balance['tuition_fee'] * $balance['total_scholar'])
                                        +
                                        ($balance['tuition_fee'] * $balance['employee_scholar'])
                                        +
                                        ($balance['tuition_fee'] * $balance['acad_scholar'])
                                        +
                                        ($balance['tuition_fee'] * $balance['family_member'])
                                        +
                                        ($balance['tuition_fee'] * $balance['nbi_alumni'])
                                        +
                                        ($balance['tuition_fee'] * $balance['cash_discount'])
                                        +
                                        ($balance['tuition_fee'] * $balance['cwoir_discount'])
                                    ) ;  */

                        $grand_total_discount += $total_discount;
                        $month_total['m1'] += $balance['month_1_payment'];
                        $month_total['m2'] += $balance['month_2_payment'];
                        $month_total['m3'] += $balance['month_3_payment'];
                        $month_total['m4'] += $balance['month_4_payment'];
                        $month_total['m5'] += $balance['month_5_payment'];
                        $month_total['m6'] += $balance['month_6_payment'];
                        $month_total['m7'] += $balance['month_7_payment'];
                        $month_total['m8'] += $balance['month_8_payment'];
                        $month_total['m9'] += $balance['month_9_payment'];
                        $month_total['m10'] += $balance['month_10_payment'];

                        $total_tuition = $balance['tuition_fee'] + $balance['misc_fee'];
                        $total_payment = $balance['month_1_payment'] + $balance['month_2_payment'] +
                                         $balance['month_3_payment'] + $balance['month_4_payment'] +
                                         $balance['month_5_payment'] + $balance['month_6_payment'] +
                                         $balance['month_7_payment'] + $balance['month_8_payment'] +
                                         $balance['month_9_payment'] + $balance['month_10_payment'] 
                                         ;

                        $grand_total_dp += $balance['total_dp'];
                        $grand_total_tuition += $total_tuition;
                        $grand_total_payment += $total_payment;//$balance['total_payment'];

                        $total_monthly = (($balance['tuition_fee'] + $balance['misc_fee']) - $balance['upon_enrollment']) / 10;
                        
                        $total_for_month = $total_monthly * (($mon_to + 1) - $mon_from);
                        
                        $total_balance = ($total_tuition - $total_discount) - ($total_payment + $balance['total_dp']);
                        /*$total_balance = $balance['month_1_payment'] + $balance['month_2_payment'] +
                                            $balance['month_3_payment'] + $balance['month_4_payment'] +
                                            $balance['month_5_payment'] + $balance['month_6_payment'] +
                                            $balance['month_7_payment'] + $balance['month_8_payment'] +
                                            $balance['month_9_payment'] + $balance['month_10_payment'] +*/
                        //$total_balance = ($total_for_month - ($total_payment + $total_discount));
                        $grand_total_balance += $total_balance;

                    ?>
                    <tr>
                        <td>{{ $Grade->where('id', $balance['grade_id'])->first()->grade }}</td>
                        <td class="text-right">{{ a_number_format($total_tuition) }}</td>
                        <td class="text-right">{{ a_number_format($balance['total_dp']) }}</td>
                        @for($i=$mon_from-1;$i<$mon_to;$i++)
                        {{--  @for($i=0;$i<10;$i++)  --}}
                            <td  class="text-right">
                                {{ a_number_format($balance[$month_array_field[$i]]) }}
                            </td>
                        @endfor
                        {{--  <td>{{ a_number_format($balance['total_payment']) }}</td>  --}}
                        <td class="text-right">{{ a_number_format($total_payment + $balance['total_dp']) }}</td>
                        
                        <td class="text-right">{{ 
                                a_number_format($total_discount)
                            }}
                        </td>
                        <td class="text-right">{{ a_number_format($total_balance) }}</td> 
                    </tr>
                @endforeach
                <tr>
                    <td>Total</td>
                    <td class="text-right">{{ a_number_format($grand_total_tuition) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_dp) }}</td>
                    @for($i=$mon_from-1;$i<$mon_to;$i++)
                    {{--  @for($i=0;$i<10;$i++)  --}}
                    {{--  @foreach ($month_total as $data)  --}}
                        <td class="text-right">{{ a_number_format($month_total[$month_field[$i]]) }}</td>
                    {{--  @endforeach  --}}
                    @endfor
                    <td class="text-right">{{ a_number_format($grand_total_payment + $grand_total_dp) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_discount) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_balance) }}</td>
                </tr>
            </tbody>
        </div>
    </body>
</html>