<!doctype>
<html>
    <head>
        <title>Student Summary Balance</title>
            {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">      --}}

        <style>
            td.rotate {
              /* Something you can count on */
              height: 190px;
              white-space: nowrap;
            }

            td.rotate > div {
              transform: 
                /* Magic Numbers */
                translate(25px, 51px)
                /* 45 is really 360 - 45 */
                rotate(-90deg);
              width: 30px;
            }
            td.rotate > div > span {
              border-bottom: 1px solid #ccc;
              padding: 50px 10px 50px;
                font-size: 35px;
                text-align: center;
                font-weight: 300;
            }
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 10px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2, .h3, h3 {
                font-size: 30px;
                font-weight: 400;
                margin-top : 0;
            }
            .container {
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
                
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 5px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-red {
                color: #a94442;
            }
            .text-green {
                color: #00a65a !important;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
            .hidden {
                display: none!important;
            }
            .td{
                vertical-align: middle;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div>
            </div>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            <br>
            {{--  <div class="text-right">Total Received Payment <strong class="text-danger"><h3>P {{ ($payment_sum->sum ? a_number_format($payment_sum->sum) : '0.00') }}</h3></strong></div>  --}}
            <br>
            <table class="table table-bordered">
                
    <tbody>
        @foreach ($Students as $student)
            <?php
                $status = true;
                $discount = 0;
                $tuition = $student->grade_tuition[0]->tuition_fee; 
                
                $discount += ($student->discount_list->scholar != 0 ? $student->discount_list->scholar * $tuition : 0);
                $discount += ($student->discount_list->school_subsidy != 0 ? $student->discount_list->school_subsidy : 0);
                $discount += ($student->discount_list->employee_scholar != 0 ? $student->discount_list->employee_scholar * $tuition : 0);
                $discount += ($student->discount_list->gov_subsidy  != 0 ? $student->discount_list->gov_subsidy  : 0);
                $discount += ($student->discount_list->acad_scholar  != 0 ? $student->discount_list->acad_scholar * $tuition : 0);
                $discount += ($student->discount_list->family_member  != 0 ? $student->discount_list->family_member * $tuition : 0);
                $discount += ($student->discount_list->nbi_alumni  != 0 ? $student->discount_list->nbi_alumni * $tuition : 0);
                $discount += ($student->discount_list->cash_discount  != 0 ? $student->discount_list->cash_discount * $tuition : 0);
                $discount += ($student->discount_list->cwoir_discount  != 0 ? $student->discount_list->cwoir_discount * $tuition : 0);
                $discount += ($student->discount_list->st_joseph_discount  != 0 ? $student->discount_list->st_joseph_discount : 0);
                               
                $tuition_fee = ($tuition + $student->grade_tuition[0]->misc_fee);
                $net_tuition = ($tuition - $discount) +  $student->grade_tuition[0]->misc_fee;
                $upon_enrollment = $student->grade_tuition[0]->upon_enrollment;
                $outstanding_balance = $net_tuition - $student->tuition[0]->total_payment;
                $tmp_tuition = (($tuition - $discount) + $student->grade_tuition[0]->misc_fee) - $student->tuition[0]->down_payment;

                $left_unpaid_down = 0;
                
                $monthly_amount = ($tuition_fee - $upon_enrollment) / 10;
                $tmp_monthly_amount = $monthly_amount;

                
                $left_unpaid_down = $upon_enrollment - $student->tuition[0]->down_payment;
                
                if ($monthly_amount > $net_tuition)
                {
                    $monthly_amount = $net_tuition;
                }

                if ($outstanding_balance == 0)
                {
                    $monthly_amount = 0;
                }

            ?>
        @if ($request['report_filter_month'] != '' && $request['report_filter_month_to'] != '')
                    @for($i=0;$i<10;$i++)
                            @if ($outstanding_balance == 0)
                            @else
                                @if ($student->tuition[0][$month_field[$i]] == $tmp_monthly_amount)
                                @else
                                    <?php $status = false; ?>
                                @endif
                            @endif
                    @endfor
                @else
                    @for($i=0;$i<10;$i++)
                    
                            @if ($outstanding_balance == 0)
                            @else
                                @if ($student->tuition[0][$month_field[$i]] == $tmp_monthly_amount)
                                @else
                                    <?php $status = false; ?>
                                @endif
                            @endif
                    @endfor
                @endif
            <tr>
                @if ($request['report_filter_month'] != '' && $request['report_filter_month_to'] != '')
                    @for($i=0;$i<10;$i++)
                            @if ($outstanding_balance == 0)
                            @else
                                @if ($student->tuition[0][$month_field[$i]] == $tmp_monthly_amount)
                                @else
                                    <?php $status = false; ?>
                                @endif
                            @endif
                    @endfor
                @else
                    @for($i=0;$i<10;$i++)
                    
                            @if ($outstanding_balance == 0)
                            @else
                                @if ($student->tuition[0][$month_field[$i]] == $tmp_monthly_amount)
                                @else
                                    <?php $status = false; ?>
                                @endif
                            @endif
                    @endfor
                @endif
                <td class="rotate">
                    <br><br><br><br>
                    @if ($status) 
                       <div><span class="text-green">PAID</span></div>
                    @else
                       <center><span class="text-red"></span></center>        
                    @endif
                </td>
                     <td style="font-size: 15px;">
                     <center><img src="{{ asset('img/header.jpg') }}" style="height: 79px; width: 600px;"></center>
                    <strong style="font-size: 19px;">EXAMINATION PERMIT - <i>{{ $months_array[$request['report_filter_month_to']-1] }} {{ \Carbon\Carbon::now('Asia/Manila')->format('Y') }} </i></strong><br><br>
                    <small style="font-size: 25px;">{{ $student->student_info->last_name . ', ' . $student->student_info->first_name . ' ' . $student->student_info->middle_name }}</small>
                          @if ($student)
                        <i><small style="font-size: 17px;">({{ $student->grade->grade . ' / ' . $student->section->section_name }})</small></i>
						@endif
						<br><br>
						<div class="col-md-6 text-right" style="line-height: 90%">
						<strong><small>JOCELYN I. TAJONERA  </small></strong>
                      <br>
					  	<small>Finance Officer/Bookkeeper</small>
						<div>

					  <center style="font-size: 8px;"><small>** NOT VALID WITHOUT SIGNATURE **</small></center>
				
                </td>
               
            </tr>
        @endforeach
    </tbody>
            </table>

        </div>
    </body>
</html>