<!doctype>
<html>
    <head>
        <title>Student Summary Balance</title>
            {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">      --}}

        <style>
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 10px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2, .h3, h3 {
                font-size: 10px;
                font-weight: 400;
                margin-top : 0;
            }
            .container {
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 5px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-red {
                color: #a94442;
            }
            .text-green {
                color: #00a65a !important;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
            .hidden {
                display: none!important;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Student Balance Summary Report</h2>
            <div>
            </div>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            {{--  <div class="text-right">Total Received Payment <strong class="text-danger"><h3>P {{ ($payment_sum->sum ? a_number_format($payment_sum->sum) : '0.00') }}</h3></strong></div>  --}}
            
                        <h2 class="text-center">Discount Summary Report</h2>
        <table class="table table-bordered">
                <tr>
                    <th>Grade</th>
                    <th class="text-center">School Subsidy</th>
					<th class="text-center">Employee</th>
                    <th class="text-center">Academic</th>
                    <th class="text-center">Family Member</th>
					<th class="text-center">NBI Alumni</th>
					<th class="text-center">Cash</th>
                    <th class="text-center">Choir</th>
                    <th class="text-center">St. Joseph</th>
                </tr>
                <tbody>
                    <?php
                        $grand_total_scholar = 0;
                        $grand_total_subsidy = 0;
                        $grand_total_emp = 0;
                        $grand_total_gov = 0;
                        $grand_total_acad = 0;
                        $grand_total_family = 0;
                        $grand_total_nbi = 0;
                        $grand_total_cash = 0;
                        $grand_total_choir = 0;
                        $grand_total_joseph = 0;
                    ?>
                    @foreach ($grade_balance as $key => $balance)
                    <?php
                        $total_subsidy = $subsidy_discount[$key];
                        $total_emp = $emp_discount[$key];
                        $total_gov = $gov_discount[$key];
                        $total_acad = $acad_discount[$key];
                        $total_family = $family_discount[$key];
                        $total_nbi = $nbi_discount[$key];
                        $total_cash = $cash_discount[$key];
                        $total_choir = $choir_discount[$key];
                        $total_joseph = $joseph_discount[$key];
                    
                        $grand_total_subsidy += $total_subsidy;
                        $grand_total_emp += $total_emp;
                        $grand_total_gov += $total_gov;
                        $grand_total_acad += $total_acad;
                        $grand_total_family += $total_family;
                        $grand_total_nbi += $total_nbi;
                        $grand_total_cash += $total_cash;
                        $grand_total_choir += $total_choir;
                        $grand_total_joseph += $total_joseph;
                    ?>
                    <tr>
                        <td>{{ $Grade->where('id', $balance['grade_id'])->first()->grade }}</td>
                        <td class="text-right">{{ a_number_format($total_subsidy) }}</td>
						<td class="text-right">{{ a_number_format($total_emp) }}</td>
                        <td class="text-right">{{ a_number_format($total_acad) }}</td>
                        <td class="text-right">{{ a_number_format($total_family) }}</td> 
                        <td class="text-right">{{ a_number_format($total_nbi) }}</td> 
                        <td class="text-right">{{ a_number_format($total_cash) }}</td> 
                        <td class="text-right">{{ a_number_format($total_choir) }}</td> 
                        <td class="text-right">{{ a_number_format($total_joseph) }}</td> 
                    </tr>
                @endforeach
                    <tr style="font-weight: bold;">
                    <td>Total</td>
					<td class="text-right">{{ a_number_format($grand_total_subsidy) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_emp) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_acad) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_family) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_nbi) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_cash) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_choir) }}</td>
                    <td class="text-right">{{ a_number_format($grand_total_joseph) }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>