<!doctype>
<html>
    <head>
        <title>Received Payment Report</title>
            {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">      --}}

        <style>
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 10px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2, .h3, h3 {
                font-size: 30px;
                font-weight: 400;
                margin-top : 0;
            }
            .container {
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 5px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-danger {
                color: #a94442;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Received Payment Report</h2>
            <div>
                @if ($range_from)
                    Date Range from 
                    {{ $range_from }}
                @endif
                @if ($range_to)
                    to 
                    {{ $range_to }}
                @endif
            </div>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            <br>
            <div class="">Total Received Payment <strong class="text-danger"> : <u>{{ ($payment_sum->sum ? a_number_format($payment_sum->sum) : '0.00') }}</u></strong></div>
            <br>
            <table class="table table-bordered">
                <tr>
                    <th>Student Name</th>
                    <th>Grade / Section</th>
                    <th>Payment Type</th>
                    <th>Payment Amount</th>
                    <th>OR Number</th>
                    <th>Date Received</th>
                    <th>Received by</th>
                </tr>
                <tbody>
                    @foreach ($StudentPaymentLog as $data)
                        <tr>
                            <td>
                                {{ $data->student->student_school_year_tag->last_name . ' ' . $data->student->student_school_year_tag->first_name . ' ' . $data->student->student_school_year_tag->middle_name }}
                            </td>
                            <td>
                                {{ $data->student->student_school_year_tag->grade->grade . ' / ' . $data->student->student_school_year_tag->section->section_name }}
                            </td>
                            <td>
                                @if ($data->payment_type == 1)
                                    <span class="">Tuition Fee Payment</span>
                                @else
                                    <span>{{ \App\AdditionalFee::ADDITIONAL_FEES[$data->payment_type]['fee_name'] }}</span>
                                @endif
                            </td>
                            <td class="text-right">
                                <span class="text-red"> {{ a_number_format($data->payment) }}</span>
                            </td>
                            <td class="text-right">
                                <span class="">{{ $data->or_number }}</span>
                            </td>
                            <td>
                                {{ \Carbon\Carbon::parse($data->received_date, 'Asia/Manila')->format('F d, Y') }}
                            </td>
                            <td>
                                @if ($data->user)
                                    <span class="">{{ $data->user->first_name }}</span>
                                @else
                                    <span>n/a</span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </body>
</html>