<!doctype>
<html>
    <head>
        <title>Student Summary Balance</title>
            {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">      --}}

        <style>
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 10px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2, .h3, h3 {
                font-size: 30px;
                font-weight: 400;
                margin-top : 0;
            }
            .container {
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 5px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-danger {
                color: #a94442;
            }
            .text-blue {
                color: #0073b7 !important;
            }
            .text-red {
                color: #dd4b39 !important;
            }
            .text-green {
                color: #00a65a !important;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Student Balance Summary Report</h2>
            <div>
                @if ($range_from)
                    Date Range from 
                    {{ $range_from }}
                @endif
                @if ($range_to)
                    to 
                    {{ $range_to }}
                @endif
                Payment Type : {{ $payment_type[$report_payment_type] }}
            </div>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            <br>
            <br>
            <?php
                $sum = 0;
            ?>
            <table class="table table-bordered">
                <tr>
                    <th>Grade Level</th>
                    <th>Total Received</th>
                </tr>
                <tbody>
                    @foreach ($grade_payments as $data)
                        <tr>
                            <td>{{ $Grade->where('id', $data['grade_id'])->first()->grade }}</td>
                            <td class="text-right"> <strong class="text-blue"> {{ a_number_format($data['total_payment']) }} </strong></td>
                        </tr>
                        <?php
                            $sum += $data['total_payment'];
                        ?>
                    @endforeach 
                    <tr>
                        <td>Total</td>
                        <td class="text-right"><strong class="text-red">{{ a_number_format($sum) }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>