<!doctype>
<html>
    <head>
        <title>Student Additional Fees Report</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style>
            @page {
                margin : 5mm;
            }
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 11px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2 {
                font-size: 30px;
                font-weight: 400;
            }
            .container {
                padding-right: 15px;
                padding-left: 15px;
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 6px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-danger {
                color: #a94442;
            }
            .text-blue {
                color: #0073b7 !important;
            }
            .text-red {
                color: #dd4b39 !important;
            }
            .text-green {
                color: #00a65a !important;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
            
            .page-break {
                page-break-after: always;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Student Additional Fees Report</h2>
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            
            <div class="text-left">Grade Level / Section  : {{ $selected_grade }} - {{ $selected_section }} </div>
            <div class="text-left">Total Paid  : <span class="text-green">{{ $paid_count }}</span> </div>
            <div class="text-left">Total Unpaid  : <span class="text-red">{{ $unpaid_count }}</span> </div>
            <br>
            <div class="text-left">Total Fees  : <strong class="text-red">{{ a_number_format($all_total_fees) }}</strong> </div>
            <div class="text-left">Total Received  : <strong class="text-red">{{ a_number_format($all_total_received) }}</strong> </div>
            <div class="text-left">Total Receivables  : <strong class="text-red">{{ a_number_format($all_total_receivables) }}</strong> </div>
            <br>
            <?php
                $over_all_books                 = 0;
                $over_all_speech_lab            = 0;
                $over_all_pe_uniform            = 0;
                $over_all_school_uniform        = 0;
                $over_all_total_additional_fee  = 0;
                $over_all_total_payment         = 0;
                $over_all_total_outstanding     = 0;
            ?>
            <table class="table table-bordered">
                <tr>
                        <th>Name</th>
                        <th>Grade</th>
                        <th>Section</th>
                        <th>Books</th>
                        <th>Speech Lab</th>
                        <th>PE Uniform</th>
                        <th>School Uniform</th>
                        <th>Total Additional Fee</th>
                        <th>Total Payment</th>
                        <th>Outstanding Balance</th>
                        <th>Status</th>
                    </tr>
                    <tbody>
                        @foreach ($Students as $student)
                            <?php
                                $total_additional_fee = 0 ;
                                $total_additional_payment = 0;
                                $outstanding_balance = 0;
                                $individual_fee = [];
                                if ($student->additional_fee)
                                {
                                    foreach ($student->additional_fee as $additional_fee)
                                    {
                                        $total_additional_fee   += $additional_fee->additional_amount;
                                        $individual_fee[]       = $additional_fee->additional_amount;
                                    }
                                    $over_all_total_additional_fee += $total_additional_fee;
                                }
                                
                                if ($student->additional_fee_payment)
                                {
                                    $total_additional_payment   += $student->additional_fee_payment->books;
                                    $total_additional_payment   += $student->additional_fee_payment->speech_lab;
                                    $total_additional_payment   += $student->additional_fee_payment->pe_uniform;
                                    $total_additional_payment   += $student->additional_fee_payment->school_uniform;

                                    $over_all_books             += $student->additional_fee_payment->books  - $student->additional_fee_payment->book_remarks;
                                    $over_all_speech_lab        += $student->additional_fee_payment->speech_lab;
                                    $over_all_pe_uniform        += $student->additional_fee_payment->pe_uniform;
                                    $over_all_school_uniform    += $student->additional_fee_payment->school_uniform;
                                }
 
                                $outstanding_balance            = $total_additional_fee - $total_additional_payment;
                                
                                if ($student->status == 0)
                                {
                                    $outstanding_balance = 0;
                                }
                                $over_all_total_payment         += $total_additional_payment;
                                $over_all_total_outstanding     += $outstanding_balance;
                            ?>
                            <tr>
                                <td>
                                    {{ $student->student_info->last_name }}, {{ $student->student_info->first_name }} {{ $student->student_info->middle_name }}
                                </td>
                                <td>
                                    @if ($student->grade)
                                        {{ $student->grade->grade }}
                                    @endif
                                </td>
                                <td>
                                    @if ($student->section)
                                        {{ $student->section->section_name }}
                                    @endif
                                </td>
                                <td class="text-right">
                                    @if ($student->additional_fee_payment)
                                        <span class="{{ $individual_fee[0] > $student->additional_fee_payment->books ? 'text-red' : 'text-green'}}">
                                            {{ a_number_format($student->additional_fee_payment->books  - $student->additional_fee_payment->book_remarks) }}
                                        </span>
                                    @endif
                                </td>
                                <td class="text-right">
                                    @if ($student->additional_fee_payment)
                                        <span class="{{ $individual_fee[1] > $student->additional_fee_payment->speech_lab ? 'text-red' : 'text-green'}}">
                                            {{ a_number_format($student->additional_fee_payment->speech_lab) }}
                                        </span>
                                    @endif
                                </td>
                                <td class="text-right">
                                    @if ($student->additional_fee_payment)
                                        <span class="{{ $individual_fee[2] > $student->additional_fee_payment->pe_uniform ? 'text-red' : 'text-green'}}">
                                            {{ a_number_format($student->additional_fee_payment->pe_uniform) }}
                                        </span>
                                    @endif
                                </td>
                                <td class="text-right">
                                    @if ($student->additional_fee_payment)
                                        <span class="{{ $individual_fee[3] > $student->additional_fee_payment->school_uniform ? 'text-red' : 'text-green'}}">
                                            {{ a_number_format($student->additional_fee_payment->school_uniform) }}
                                        </span>
                                    @endif
                                </td>
                                <td class="text-right">
                                    <strong class="text-red">{{ a_number_format($total_additional_fee) }}</strong>
                                </td>
                                <td class="text-right">
                                    <strong class="text-green">{{ a_number_format($total_additional_payment) }}</strong>
                                </td> 
                                <td class="text-right">
                                    <strong class="text-blue">{{ a_number_format($outstanding_balance) }}</strong>
                                </td>    
                                <td class="">
                                    @if ($student->status == 0)
                                        <span class="text-red">Inactive</span>
                                    @else
                                        @if ($outstanding_balance > 0)
                                            <strong class="text-red">Unpaid</strong>
                                        @else
                                            <strong class="text-green">Paid</strong>
                                        @endif
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        <tr>
                            <th colspan="3">
                                Total
                            </th>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_books) }}</strong>
                            </td>
                            <td class="text-right">  
                                <strong class="text-red">{{ a_number_format($over_all_speech_lab) }}</strong>
                            </td>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_pe_uniform) }}</strong>
                            </td>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_school_uniform) }}</strong>
                            </td>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_total_additional_fee) }}</strong>
                            </td>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_total_payment) }}</strong>
                            </td>
                            <td class="text-right">
                                <strong class="text-red">{{ a_number_format($over_all_total_outstanding) }}</strong>
                            </td>
                            <td></td>
                        </tr>
                    </tbody>
            </table>
            
        </div>
    </body>
</html>