<!doctype>
<html>
    <head>
        <title>Summary Per year Level</title>
           {{--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">     --}}

        <style>
            @page {
                margin : 2mm;
            }
           body {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 11px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            .h2, h2 {
                font-size: 30px;
                font-weight: 400;
            }
            .container {
                padding-right: 15px;
                padding-left: 15px;
                margin-right: auto;
                margin-left: auto;
            }
            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                            
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
                border: 1px solid #ddd;
            }
            .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
                padding: 6px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
            .text-danger {
                color: #a94442;
            }
            .text-right {
                text-align: right;
            }
            .text-center {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 class="text-center">Summary Per year Level</h2>
            {{--  <div class="text-right">Total Tuition Balance <strong class="text-danger">{{ a_number_format($StudentTuitionFee->total_tuition_balance) }}</strong></div>
            <div class="text-right">Total Other Balance <strong class="text-danger">{{ a_number_format($StudentTuitionFee->total_additional_fee) }}</strong></div>
            <div class="text-right">Total Balance <strong class="text-danger">{{ a_number_format($StudentTuitionFee->total_additional_fee + $StudentTuitionFee->total_tuition_balance)}}</strong></div>  --}}
            <div class="text-right">Date Generated : {{ \Carbon\Carbon::now('Asia/Manila')->format('m, d, Y h:i a') }}</div>
            <div class="text-right">Generated By   : {{ Auth::user()->first_name .  ' ' . Auth::user()->last_name }}</div>
            <br>
            <table class="table table-bordered">
                <tr>
                    <th>Grade Level</th>
                    {{--  <th> Section</th>  --}}
                    <th>No. of Student</th>
                    <th>Total Tuition</th>
                    <th>Total Misc Fee</th>
                    <th>Total</th>
                    <th>Total Gov't Subsidy</th>
                </tr>
                <?php
                    $total_students = 0;
                    $total_tuition = 0;
                    $total_misc = 0;
                    $over_all_total = 0;
                    $over_all_gov_subsidy = 0;
                ?>
                @foreach ($grade_payments as $data)
                    <?php
                        $total_students += $data['no_of_students']; 
                        $total_tuition += $data['total_tuition'];
                        $total_misc += $data['total_misc'];
                        $over_all_total += $data['total_tuition_fee'];
                        $over_all_gov_subsidy += $data['total_gov_subsidy'];
                    ?>
                    <tr>
                        <td>
                            {{ $Grade->where('id', $data['grade_id'])->first()->grade }}
                        </td>
                        <td class="text-right">
                            {{ $data['no_of_students'] }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($data['total_tuition']) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($data['total_misc']) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($data['total_tuition_fee']) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($data['total_gov_subsidy']) }}
                        </td>
                    </tr>
                @endforeach
                    <tr class="text-danger">
                        <td>Total</td>
                        <td class="text-right">{{ $total_students }}</td>
                        <td class="text-right">
                            {{ a_number_format($total_tuition) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($total_misc) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($over_all_total) }}
                        </td>
                        <td class="text-right">
                            {{ a_number_format($over_all_gov_subsidy) }}
                        </td>
                        {{--  <td>
                        </td>
                        <td>
                            {{$section_selected}} 
                        </td>
                        <td>{{ a_number_format($over_all_tuition_sum) }}</td>  --}}
                        {{--  <td>{{ a_number_format($over_all_discount_sum) }}</td>
                        <td>{{ a_number_format($over_all_net_tuition) }}</td>
                        <td>{{ a_number_format($over_all_paid_fee) }}</td>
                        <td>{{ a_number_format($over_all_add_fee) }}</td>
                        <td>{{ a_number_format($over_all_add_paid_fee) }}</td>
                        <td>{{ a_number_format($over_outstanding_balace) }}</td>  --}}
                    </tr>
            </table>
        </div>
    </body>
</html>